# Generated by Django 3.0.8 on 2020-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_auto_20200728_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
