# Generated by Django 3.0.8 on 2020-07-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_colis_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='client',
        ),
    ]
